language: python
os: linux
dist: bionic
sudo: required
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3.5-6.0"
install:
  - apt-get install libmemcached-dev memcached redis-server
  - pipenv install --dev
  - pip install coveralls
  - pip install --editable .
script: pytest
after_success:
  - codecov
cache:
  directories:
    - $PIP_CACHE_DIR
    - $PIPENV_CACHE_DIR
env:
  global:
    - PIP_CACHE_DIR=$HOME/.cache/pip
    - PIPENV_CACHE_DIR=$HOME/.cache/pipenv
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1